import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

import Layout from "../components/layout";
import Sidebar from "../components/sidebar";

import styles from "../styles/Home.module.css";

export default function Index() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to{" "}
          <Link href="https://nextjs.org">
            <a>Next.js</a>
          </Link>
        </h1>

        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          <div className={styles.card}>
            <Link href="https://nextjs.org/docs">
              <a>Documentation &rarr;</a>
            </Link>
            <p>Find in-depth information about Next.js features and API.</p>
          </div>

          <div className={styles.card}>
            <Link href="https://nextjs.org/learn">
              <a>Learn &rarr;</a>
            </Link>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </div>

          <div className={styles.card}>
            <Link href="https://github.com/vercel/next.js/tree/canary/examples">
              <a>Examples &rarr;</a>
            </Link>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </div>

          <div className={styles.card}>
            <Link href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app">
              <a>Deploy &rarr;</a>
            </Link>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </div>

          <div className={styles.card}>
            <Link href="/root">
              <a>My Lab &rarr;</a>
            </Link>
            <p>Learning Next.js by Official Docs. See my example files here.</p>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <Link
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          <a>Powered by Vercel</a>
        </Link>
      </footer>
    </div>
  );
}

Index.getLayout = function getLayout(page: any) {
  return (
    <Layout>
      <Sidebar />
      {page}
    </Layout>
  );
};
